---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mvilliger/artillery-docker
    tag: "latest"

inputs:
- name: application
- name: current-app-info

run:
  path: application/demos/cicd/bg-app-deploy/ci/tasks/load-tests
