---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: application
- name: current-app-info

run:
  path: application/demos/cicd/bg-app-deploy/ci/tasks/update-routes
